travis:
  secure:
    BINSTAR_TOKEN: Q0AN9H3ckPsmmmVxUtjsPhhRTMuG/Pc/Fc745ApNt9ZRUQmw/t1+a+whJ2fYtl5k4S+NzYKhdpnbf3gEvjeKzrEvPhVMyx7h9vlfQLhi7zSIMgYVE92PrzrtUkBkq4e3ao9pS+90ferw9seXcmDU0eCgKOWMDqDDifs5CaPuBsS9t9bAJDAb7nvC+vvRkCXbsp2zdaoE9DzC+hPO9N2fc/zx2UrL/4dRvNE/Htzw5cfu7XfzaP2vJJtoX/cQJ76U9yPe2phiO90KTcZvjxMDYxTHRfwCQyv292ns1AIrudgickKxrAljLm+i1Wp8xRlLGZz4QdiQO4xa1ARsHdRmsYUFPCsmn4J0L7+HqODFd4rvrlTvC6xg1CvB+vRi3wI8QM7bq4fJ92SmVkbRFWgH5hZdU8KcaXjnRBeJQyvO84Sf4Df/8IClCdeiRgJ8PIi9CNVH/pdux31/BVpxaTK6I2If/t0y4jcecwGvRMs44z0MCseqZ3wgNCpfP4fz8Aw4d1Rjtgss6myUDwLseXM0KeTP4XQ7LJqLl1Jj5XcWGZl1dtQA6g7Iz2tjGeVgXr81aIrSlnFDcp8ISwx2DZbCwWtKafNaaVEjxuIFL2d0D+5Pfb3GZOKr0WgHrRZ2PbDfdJigoFljFpbWCD54b04+PS7+J6MoJ9vX/XmbVWhEbFc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
