appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: U9pJqXFSkSjbRyscUv53UVCjTWMAYLGjfTIl28iI4mBgKrLRwzKytKnODHJvyCyVuoLU6msOqBnMEBWBIQdCAlShsNrwtyFi+n2dZb+qQVghGQFYqdq6MVpksUegC63DhH4YyxsITcVDKUq1tAlxoyMPX9HH+eYtKqs2WV6dxSaVzqwAUcJXnUc8hGkxk5AGI6jqPGXinXAiB13w5KUO6ArNVapRjtjRJ2F9KZNRu2u4lvJi7igUIQEgiR2yuGN0zdFApJNTN8Y8bYfFQuR6O9XrTsVHlKUcgGhMi6rQW846g2sewy9zBsim4zG+95dVR39KUrIj0CqfC0SD74WuP3Kwb056dEdb4WVr2eayy+SU962jA+P30WXBU28PjRB/+zJG9h21aC1UmJjUzUDHWewjaStt6vhLizZHf/qYFLgaOT8XB6DrfuQe4SJh3zXyFSgDz+ZoYJh7Qv2CWgzLF/RRdiJasDWAw1KVehdd+k6kbv47mreVEo3hJDy+vkQ1UXWzjXsYO96RsS359vwRwRWkmgfM5ixlhZgwepHPMG3468iIn/zEpA1kFCvu07hHAZ+efa198qKp0KtujCLgVFDTS/gHPyK+hnzR4fxoIctfokK1ug/pEZT98zjl1iWYdzisWaTY9HjCD+/vG7fQ6Su7znK3HGeU6XJ0vRg0neY=
conda_forge_output_validation: false
